### ISSUE TITLE
Feature Request: Hide the Hide Message

### ISSUE THREAD

**Issue by PitchBright** [skmedix/HideNames#3]
Can you add a command (or config option) to hide the message that tells people their HideName status when they join a world? Extremely useful for admins that want to cut down on login message clutter, and servers that have players that already know their names are permanently disabled.

1.7.10 too... please and thanks!

Cheers,
Pitch

**Comment by skmedix** [comment]
Yeah, no problem. But for 1.7.10.. I have to backport all the changes from the newest version. I'll do it in the next week.

**Comment by PitchBright** [comment]
Awesome! Thanks!

**Comment by skmedix** [comment]
Delayed. Sorry. Expect an update in the next week.

**Comment by PitchBright** [comment]
Okay, thanks for the update!

**Comment by PitchBright** [comment]
Bump :)

**Comment by skmedix** [comment]
Yeah, yeah.. ;)

**Comment by PitchBright** [comment]
Beauty! Thanks mang :)

**Comment by skmedix** [comment]
> Backporting to older versions

**Comment by skmedix** [comment]
**Backports:**
- [x] 1.10.2
- [ ] 1.9.4
- [ ] 1.8.9
- [x] 1.7.10
